### ISSUE TITLE
Possible to use this Godot4 KD-Tree GDExtension?

### ISSUE THREAD

**Issue by GeorgeS2019** [Remi123/MotionMatching#11]
https://github.com/paxwort/GD-KD-Tree

**Comment by Remi123** [comment]
While it's the exact version of this library that I use, he doesn't expose half of the features this library expose.

**Comment by GeorgeS2019** [comment]
@fire 

Do you see the benefit of replacing the KD-tree used here with what is available as the GDExtension?

If the GDExtension version is inadequate, do you see adding the missing features to the GDExtension version so the whole Godot community has the first-in-class KD-tree in the community standard: GDExtension

**Comment by fire** [comment]
I would rather focus on the demo first, this is a sidequest that isn’t directly related.
