### ISSUE TITLE
Use Github Actions to have Builds of the addon

### ISSUE THREAD

**Issue by ywmaa** [Remi123/MotionMatching#6]
Do you mind if I make a pull request ? and make a github workflow similar to this :

https://github.com/CoaguCo-Industries/GodotSteam/tree/v4.2.5-gde/.github/workflows

So we can have tests for most platforms ? 
And probably have a release option.

**Comment by Remi123** [comment]
@ywmaa 
Please do ! I'm not very familiar with the github Action setup.

Things to consider : I have a dependency on the C++ Boost Library. You can check my yml on how I include it. 
Basically I found an action to download boost with some caching, and it output the path to the boost directory as boost_root. I use this directory in my call to scons with Boost_DIRECTORY=BOOST_ROOT or something like that.

Other than that, you shouldn't encounter any problem.

I'm currently updating the wiki and I'll keep you updated on how to use my framework.

**Comment by fire** [comment]
Completed

**Comment by ywmaa** [comment]
Thanks @fire, I got busy with other stuff like vertex_lighting, that I forgot to try GD Extension and try make a github build for it.
